### PR TITLE
Replace jboss soap with latest jaxws rt

### PR DESCRIPTION
**Pull request by kurtlenfesty**
Branch rebased. Ready to merge into master.

Fixes:

- https://github.com/DIA-NZ/webcurator/issues/90
- https://github.com/DIA-NZ/webcurator/issues/87

### CODE REVIEW

**Comment by obrienben** [comment]
Re the failed Travis build - @hannakoppelaar any ideas how we can get travis to find the dps-sdk-fat-all jar? How did you get it to find the other non-maven dependencies originally?

**Comment by kurtlenfesty** [comment]
Hmmmm. It would have had to run that script to load the dependencies. Maybe there's a part of the travis setup that runs that script. I can check that.

**Comment by kurtlenfesty** [comment]
Yes, it's the .travis.yml file in wct-parent. I'll update it so that it loads that dependency as well.

**Comment by kurtlenfesty** [comment]
It gets triggered automatically every time a commit is pushed... still fixing it, though.

**Comment by kurtlenfesty** [comment]
It seems to be fixed now. Since Hanna has merged that other pull request, should I rebase this branch, re-create the pull request for merge, @obrienben ?

**Comment by obrienben** [comment]
@kurtlenfesty yes please

**Comment by kurtlenfesty** [comment]
Rebasing branch. Will recreate pull request.

**Pull request closed without merging**
