### PR TITLE
Feature/d1.3 qa tree view h3 compat

### PR DESCRIPTION
**Pull request by hannakoppelaar**
Note that importing resources into a harvest (in the Tree View) doesn't work, but this problem already existed in master. I will create a separate issue for this.

### CODE REVIEW

**Comment by obrienben** [comment]
I'm getting an error when trying to prune. Does it work for you?
My steps:
1. select resource
2. click 'Prune Single Item'
3. enter Provenance Note
4. click save

From the UI there's just a generic InvocationTargetException. But the error seems to be originating from the wct-store side, it's throwing an IllegalAccessError at line 675 in ArcDigitalAssetStoreService for the lib org/archive/uid/UUIDGenerator. I checked that webarchive-commons was packaged with the war file and it is, so I'm interested to hear if you have the same problem.

**Comment by hannakoppelaar** [comment]
It works on my side, but I've only tested with jetty. I will see if I can reproduce this with tomcat.

**Comment by hannakoppelaar** [comment]
I'm deploying the wars in a single Tomcat 8 instance now, and I'm still able to prune/add resources from/to the tree. I did find a different bug, though, but that was a null pointer.

Perhaps you have an old version of the UUIDGenerator class lying around? Perhaps the old H1 lib is also being included in your war?

**Comment by hannakoppelaar** [comment]
O I just noticed that aheritrix.jar is indeed packaged in wct-store.war. This might be your problem.

**Comment by obrienben** [comment]
Hmm but is it not packaged in your one as well?

**Comment by hannakoppelaar** [comment]
Yeah, perhaps there's a difference in class loading order between our platforms or tomcat versions? Anyway, we can simply remove the old jar from wct-store.war and hopefully that will fix your problem?

**Comment by obrienben** [comment]
It was still being included through the submit-to-rosetta module, which I'm guessing you wouldn't need. So I've swapped the aheritrix dependency within that to webarchive-commons, and that's fixed the original error.

**Pull request merged**
