### PR TITLE
Feature/d1.4.6.3 xml editor profile overrides in the target summary

### PR DESCRIPTION
**Pull request by kurtlenfesty**
This is based on D1.4.6.2, so that pull request would need to be merged first.

See [D1.4.6.3_xml_editor_profile_overrides_in_the_target_summary](https://github.com/DIA-NZ/webcurator/tree/feature/D1.4.6.3_xml_editor_profile_overrides_in_the_target_summary) for the actual branch.

Note that this version only overrides and validates profile overrides for the selected profile. For imported profiles, validation takes place whether or not the profile has been overridden (so when there isn't a override, it will validate the imported profile).

Note, there is an issue that on the Target page, Profile tab, when saving the profile on a imported profile, that the POST seems to occur twice, so this issue will need to be solved before this pull request is merged.

### CODE REVIEW

**Comment by hannakoppelaar** [comment]
I think this is functionally okay: updates to the raw profile on the qa ti summary page go to the profile overrides of the target.

One confusing thing on this page, however, is the fact that the profile string shown is always a base profile, even if the target already has an overriding profile. This means that, after you've applied the profile overrides and the page has reloaded, you don't see the profile that you've just updated, but one of the base profiles. Perhaps we could follow the same strategy here as on the target profile tab (target-profile.jsp): don't update the textarea on page load (in the JavaScript function toggleProfileOverrides), but use the h3RawProfile attribute of the ProfileCommand as its source.

A minor issue is the CodeMirror style: the "elegant" theme used here, is used on the target and target instance pages to indicate that the editor is in read-only mode. The editing mode uses the default style.

**Comment by kurtlenfesty** [comment]
I've removed the 'elegant' theme.

For the Target Summary page I've had it preserve the state of the editor when switching between different base profiles.

@hannakoppelaar I've looked at your last comment about showing the base profile after the page has reloaded--I'm not sure if you're referring to the Target Summary page or the Targets page, Profile tab.

I've noticed that the Targets page, Profile tab will show the correct profile override as set by the Targets Summary page _initially_, but if you switch to a different base profile and then back to the imported profile override, it will show the imported base profile default, without the target changes.

So I think this will have to be fixed as well so it shows the correct override profile. Maybe I should put similar logic as I put in qa-ti-summary.jsp? Let me know if you want me to do that as well.

**Comment by hannakoppelaar** [comment]
> @hannakoppelaar I've looked at your last comment about showing the base profile after the page has reloaded--I'm not sure if you're referring to the Target Summary page or the Targets page, Profile tab.
> 
> I've noticed that the Targets page, Profile tab will show the correct profile override as set by the Targets Summary page _initially_, but if you switch to a different base profile and then back to the imported profile override, it will show the imported base profile default, without the target changes.
> 
> So I think this will have to be fixed as well so it shows the correct override profile. Maybe I should put similar logic as I put in qa-ti-summary.jsp? Let me know if you want me to do that as well.

Initially, I wasn't bothered by the overriding profile not returning when you go back to the original base profile (on the profile tab of the target/target instance page), but now that I've seen your change in the ti summary page, I do feel it makes more sense to have it work that way.

So, yeah, it would be great if you could add the same logic to target-profile.jsp.

**Comment by kurtlenfesty** [comment]
Okay, @hannakoppelaar, I'll try to get that change to you in the next couple of hours.

**Comment by hannakoppelaar** [comment]
This looks okay to me.

**Pull request merged**
